### ISSUE TITLE
server-nodejs

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#12]
Create a "server-nodejs" directory that will hold the file of the new NodeJS server like this:

        `-- damas-core/
            |-- server-nodejs/
            |   |-- model.js           -- mongodb / mongoose data model
            |   |-- package.json
            |   |-- routes.js          -- controllers for our server (CRUD for now)
            |   `-- server.js          -- main executed file
Write the CRUD methods for our service (see the existing methods in the Php) in model.js, routes.js. server.js is containg the express server, listening to the 80 and 443 ports.

The package.json file contains something like this:

        {
          "name": "damas-nodejs",
          "version": "0.0.1",
          "description": "damas server implemented in NodeJS",
          "dependencies": {}
        }

GOALS: run a REST NodeJS server containing exposing the create, read, update, delete methods of the data model using the HTTP methods GET POST PUT DELETE. Also implement a POST only interface to support HTML forms.

Debug the REST server using the curl command line tool (see http://curl.haxx.se/)

@jogal360 @Baenshee

**Comment by remyla** [comment]
server.js file should be index.js

**Comment by Baenshee** [comment]
server.js has been renamed to index.js
