### ISSUE TITLE
Update the client update and graph methods

### ISSUE THREAD

**Issue by gnoxr** [remyla/damas-core#139]
This issue is about an update breaking the compatibility with existing clients, in order to provide a more advanced `update` method, and thus changing its profile from:

``` javascript
update(ids, keys[, callback])
graph(ids[, callback])
```

To:

``` javascript
update(nodes[, callback])
graph(ids[, depth[, callback]])
```

The `experimental` server is already compatible with these changes. The problem is that the existing clients based on damas libraries need to be updated accordingly.

It allows sending multiple different update operations at once (silly example: incrementing a value in multiple different nodes). The `_id` key inside of an object may contain an array of ids.

**Comment by remyla** [comment]
/api/update is now compliant with those specs

/api/graph depth is less prioritized now, closing the issue. Thanks!
