### ISSUE TITLE
cli: realpath on unexistent file does not succeed

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#150]
we have this following sequence

when we delete a file from the file system, we intercept it with inotify

``` sh
EVENTS="close_write,moved_to,moved_from,delete"
inotifywait --exclude "/\..+" -r -m -e "$EVENTS" --timefmt '%s' --format '%e %T %w%f' "$DIR" > "$FIFO" &
```

and write a message on the file

``` sh
    if [ $event = "DELETE" ]
    then
        echo $event
        damas write -m "file deleted <i>($event)</i>" $file
    fi
```

we deleted these 3 files, manually using rm -rf on a parent dir, which produces this log:

```
DELETE 1469784893000 /PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz.2.ma
DELETE 1469784893000 /PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz.2.log
DELETE 1469784893000 /PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz_160718_ren.mov
```

and the call to realpath on the non-existent file fails

```
realpath: ‘/PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz.2.ma’: No such file or directory
realpath: ‘/PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz_160718_ren.mov’: No such file or directory
realpath: ‘/PRODUCTIONS/wf/sh/sc0012/pvz/wf_sc0012_pvz.2.log’: No such file or directory
```

therefore the created message shows a / for the #parent key instead of the file path like `/wf/sh/sc0012/pvz/wf_sc0012_pvz.2.ma`

```
[{"author":"damas","time":1469784895573,"comment":"file deleted <i>(DELETE)</i>","#parent":"/","_id":"579b233f463c265e1d8bd0bd"}]
[{"author":"damas","time":1469784895574,"comment":"file deleted <i>(DELETE)</i>","#parent":"/","_id":"579b233f463c265e1d8bd0be"}]
[{"author":"damas","time":1469784895574,"comment":"file deleted <i>(DELETE)</i>","#parent":"/","_id":"579b233f463c265e1d8bd0bf"}]
```

**Comment by zankia** [comment]
Well this will be hard to recover path to file if it doesn't exist...
I don't know what's in `$file` but I believe we can upgrade [get_real_path](https://github.com/remyla/damas-core/blob/experimental/cli/damas.sh#L199) with something like ` || $1`

**Comment by remyla** [comment]
yes as far as we have absolute pathes as input (inotify sends absolute pathes) it could be possible to straightforwardly substitute the repo root from the path to obtain the relative path we want
