### ISSUE TITLE
cli: test if assets in db

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#151]
in the project root we can use damas read to check if an asset is correctly indexed in db

``` sh
$ find . -type f -exec damas read {} \;
[...]
[{"author":"damas","time":1470302251478,"_id":"/wf/sc/sc0014/sc0014-sh0140/edt/wf_sc0014-sh0140_edt.1.mov"}]
Read error: Not found
Read error: Not found
[{"author":"damas","time":1470302258945,"_id":"/wf/sc/sc0014/sc0014-sh0440/snd/wf_sc0014-sh0440_snd.1.wav"}]
[...]
```

instead of Read error: Not found we could have a text containing the path which was not found, like `ls` in order to process it if needed

``` sh
$ ls -l ./path/to/filenotexists
ls: cannot access ./path/to/filenotexists: No such file or directory
```

or does a `damas status`, like `git status`, to see a list of `Untracked files` makes sense? (as it could be very slow..)

**Comment by zankia** [comment]
Hello,

I just thought of an other approach.
As you can add files with inotify, it could be possible to add untracked files in DB with a special key.
Once the file is added using damas create, the latter key is removed.
damas status becomes a read on the key

**Comment by remyla** [comment]
Hi,

inotify is not mandatory, and could fail (for example if it reaches the maximum number of watched directories, or if the watching process stops for any reason) thus this is why having a way to list untracked files would be very useful

let me try to expand the idea a bit here..

```sh
damas untracked .
```
would parse the current directory, recursively, and list the files (full path from repo root? or relative path like git status does?) which are not tracked yet

then a very nice thing would be to be able to pipe an action in damas again as explain here #168  ?
```sh
damas untracked . | damas add
```

thank you

**Comment by zankia** [comment]
`damas untracked .` would be the same as `find . -type f -exec damas read {} \;`

The main problem here is the slowness. In my idea, the database stores every file of the subdirectories and they stay untracked until they got added.
`damas untracked` becomes a `damas search "status:untracked"` or something like that

**Comment by remyla** [comment]
Let's say we have a repo with hundreds of directories, and one file is somewhere, untracked (which means: no record in the respective database), and we would to know about this file with a command that damas.sh would provide. what would it be?

Please have a look at my first comment again: the find command is fine for some purpose, I actually use it, but it is not convenient to list untracked files because it is saying `Read error: Not found` instead of giving the file path.

If you have a record of the file in the database, and put a key "status:untracked" on it, well, that means that this file is actually tracked.

**Comment by remyla** [comment]
Here is the script I use to find every untracked file on the White Fang project:

```sh
#!/bin/bash
#
# Scan local repo folders and output missing paths in db
#
echo -n "# Listing every file on disks in repo..."
cd /PRODUCTIONS
find wf -exec echo {} \; > /tmp/everything
echo `cat /tmp/everything | wc -l` files.
echo "# Querying database for untracked files:"
while read line; do
    damas-experimental read $line
    if [ "$?" != "200" ]; then
        echo $line
    fi
done < /tmp/everything
echo "# Done."
```

Which is ran with a modified version of damas.sh (pointed by /usr/bin/damas-experimental) not commited yet, related to #157 issue:

```sh
 damas_read() {
   get_ids $@
   RES=$(curl -w "%{http_code}" -o /dev/null -ks -H "$AUTH" -H "$JSON" -d "$IDS" $URL'read/')
   exit $RES
 }
```

**Comment by zankia** [comment]
I meant even if you have the same input as ls if an error occurred, which is great, it would take about the same time for trying to read nodes of every files.
The goal in tracking every file even if they are not known in the project is to provide a command that would give a list of files with a simple search.
Maybe I misunderstood the reason of this issue, but I think there is no need to modify the CLI on order to improve your solution

**Comment by remyla** [comment]
The fact is that I need to make evolve the CLI, that is the reason why this issue exists. The CLI is ran in production scripts everyday here, that might explain why I have precise points to address about it. I try to describe the problem and a way to solve it, sorry if I don't manage well enough here. Please ask questions if you intend to get deeper in there. Thank you for your time.

**Comment by remyla** [comment]
this issue is partially solved since we exposed the server error codes in #157, we can test the 0 exit value when doing a read on a file, as explained above

**Comment by remyla** [comment]
fixed in https://github.com/remyla/damas-core/commit/bb4e0ed318496954caa60820364e83d8feba3251
