### ISSUE TITLE
cli: better exit status codes

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#157]
example:

``` sh
$ damas add bird.blend 
Create error: Conflict
```

returns 0 but should return an exit code != 0

also, the signin action returns 0 if the signin failed

=> revise all error code returned

**Comment by remyla** [comment]
The damas.sh command could return the HTTP status codes for single operations (CRUD, etc) on the server.
This could be useful to perform a read on a filename in order to know if the file is identified (200) or unknown (404)

For this, curl has this useful command line parameter: -w "%{http_code}"
http://superuser.com/questions/272265/getting-curl-to-output-http-status-code

**Comment by zankia** [comment]
You can indeed get the status code with `-w "%{http_code}"`. But it will be outputted in stdout, at the end of the response. So you will need to remove the 3 last characters from the response and

* if code < 300 -> do nothing
* else -> set [errno](https://linux.die.net/man/3/errno) to the status code

**Comment by remyla** [comment]
ty!
here is a sample in order for read to return the right exit code (thus this is breaking output)

```
damas_read() {
    get_ids $@
    #RES=$(curl -w "\n\n%{http_code}\n" -ks -H "$AUTH" -H "$JSON" -d "$IDS" $URL'read/')
    RES=$(curl -w "%{http_code}" -o /dev/null -ks -H "$AUTH" -H "$JSON" -d "$IDS" $URL'read/')
    exit $RES
    if [ $HUMAN ]; then
        parse_json "$RES"
        RES=$PARSED
    fi
}
```

**Comment by remyla** [comment]
Unfortunatly, the exit code is actually made of 2 Bytes on Unixes, and thus can't be greater than 255. Therefore the HTTP error codes received from the server could not be directly passed to the value of exit.

http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF

**Comment by remyla** [comment]
here are the mapped error values (available from the next commit):
```
EXIT VALUES
   0  Success
   1  Syntax or usage error
   2  Not a damas repository (or any parent)
   3  Server is unreachable
   7  (Server 207) Multi-Status (some nodes do not exist)
   40 (Server 400) Bad request (not formatted correctly)
   41 (Server 401) Unauthorized
   43 (Server 403) Forbidden (the user does not have the right permission)
   44 (Server 404) Not found (all the nodes do not exist)
   49 (Server 409) Conflict (all nodes already exist with these identifiers)
   50 (Server 500) Internal server error
   60 (Server xxx) Unknown server error
```
