### ISSUE TITLE
cli: read any node by its identifier

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#170]
Using the CLI we would like to be able to read any node on a server providing its identifier. The current `damas read` command translates file names, which is fine to retrieve assets, but which prevents reading arbitrary nodes by using their exact identifier. For example, a node `tnzpv` is in our database and we would like to access it, but right now:
```sh
$ damas read tnzpv
Read error: Not found
```
In the server log:
```
[ '/tnzpv' ]
POST /api/read/ 404 1.322 ms - 21
```

A solution would be to separate a regular read command (which exposes the server read operation that reads any identifier) and another command which actually translates the provided argument to an asset identifier?

**Comment by zankia** [comment]
Or it should be possible to verify if the file exists while getting the relative path. If there is no file, there is no need to get a relative path.

**Comment by remyla** [comment]
does your proposal is describing a complete solution?

providing we have:
```json
{
"_id":"tnzpv",
"comment":"node1"
}
{
"_id":"/root/folder/tnzpv",
"comment":"node2"
}
```
and
```sh
 echo $PWD
/root/folder/tnzpv
```
how would the solution you propose behave on executing `damas read tnzpv` if:
- the file exists
- the file doesn't exist

**Comment by zankia** [comment]
Well, if you are in `/root/folder/tnzpv`, the file does exist. But assuming you are in `/root/folder`, the behavior would be :

* Read node 1 if `tnzpv` doesn't exist
* Read node 2 if `tnzpv` exists

**Comment by remyla** [comment]
the proposed solution is to expose the CRUD operations of the server without processing the JSON input (thus we obtain something that is generic) while adding more specific commands to process file inputs (`damas read <JSON>` is generic while `damas show <file(s)>` process the filesystem wildcards before calling the server-side read operation). This solution is easy to implement and understand which tends to adress the problem correctly. The same happens for create/add commands: `create` is the generic command which allow us to create any node, like with /api/create. the `add <file>` command is accepting file wildcards as input, which are processed before calling the server-side `create` operation.

``` 
COMMANDS
 13   File commands:
 14      add     Add files to the index
 15      init    Prepare the current directory adding a .damas/ repo folder
 16      lock    Lock files (set key 'lock' = user name)
 17      rm      Remove files from the index
 18      show    Show files record
 19      signin  <username> <pass>
 20      signout Remove authorization token
 21      stats   Update file_mtime and file_size keys of files
 22      unlock  Unlock files
 23
 24   CRUDS commands (send JSON to the server, see examples below):
 25      create       <json>  create node(s)
 26      read         <json>  show the keys of the file
 27      update       <json>  update nodes
 28      delete       <json>  delete nodes
 29      search       <query> search
 30      search_mongo <query> <sort> <limit> <skip> MongoDB search - beta
```

this is available from the next commit

**Comment by remyla** [comment]
fixed in https://github.com/remyla/damas-core/commit/bb4e0ed318496954caa60820364e83d8feba3251
