### ISSUE TITLE
server-nodejs: Signal handling

### ISSUE THREAD

**Issue by zankia** [remyla/damas-core#180]
It would be easier for production servers to indicate if there are able to stop.
By implementing signal handling, it would be possible to finish all current processes and don't accept anymore in order to gently stop the server.
There won't be any need to check if everything is ok before using CTRL + C

Node.js can handle signal easily like this :
```javascript
process.on('SIGINT', () => {
  console.log('Received SIGINT.');
});
```
https://nodejs.org/api/process.html#process_signal_events

**Comment by remyla** [comment]
I agree, it would be very nice to have this
