### ISSUE TITLE
cli: search_mongo

### ISSUE THREAD

**Issue by zankia** [remyla/damas-core#186]
Hello,
I can't manage to get search_mongo working. 
Is it working well ? How does it work ?
Maybe this could be documented...

**Comment by remyla** [comment]
Hello,

You have an access to some interfaces which are using it in production everyday, it works well there.

The available doc is merely https://github.com/remyla/damas-core/wiki/API-reference#search_mongo
Which may not be sufficient, in that case it could be interesting to understand where it is blocking for you. Could you describe more the calls you want to make and what you get?

**Comment by zankia** [comment]
Here is what I do in javascript:
```javascript
damas.search_mongo({"email_daily_report": true}, {file_mtime: -1}, 100, 0);
```
I get 2 node ids

But with the CLI:
```bash
damas search_mongo '{"email_daily_report":true}' '{"file_mtime":-1}' 100 0
```
I get nothing

The first query interpreted by the server is
```json
{ "query": { "email_daily_report": true }, "sort": { "file_mtime": -1 }, "limit": 100, "skip": 0 }
```
and the second is
```json
'{"query": {"email_daily_report":true}, "sort": {"file_mtime":-1}, "limit": 100, "skip": 0}': ''
```

**Comment by zankia** [comment]
By the way, I managed to query the server with curl
```bash
curl -ks -H "Content-Type: application/json" -X POST http://localhost/api/search_mongo -d '{"query": {"email_daily_report":true}, "sort": {"file_mtime":-1}, "limit": 100, "skip": 0}'
```
So there is something that goes wrong when using damas CLI I think

**Comment by zankia** [comment]
For no known reason, when using this `damas mongo_search` the request is sent as x-www-form-urlencoded whereas when using the **exact** same curl command, the request is sent as json
