### ISSUE TITLE
server-nodejs: permissions per node author key

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#189]
In addition to the current per operation permission system,

we would like to filter the ability to perform some actions using the value of the `author` key on nodes.

* the involved operations would be `/api/read` and `/api/update`
* we compare the authenticated username:
    * if username === author then we allow calls to /api/read and /api/update (even if user class is not editor nor admin) on this node 
    * if username != author then a null is returned by /api/read for this node, and a 403 permission denied is returned for calls to /api/update

> implementation note 1: the functions should be considered as filtering function, taking an input (objects, arrays) and returning and output (filtered input). Therefore the implemented code should not be inserted in existing functions, only the call to filtering functions.

>  implementation note 2 (not really sure of this one): the code could reside in permissions.js

> note 3: this permission system can be enabled from config

**Comment by zankia** [comment]
Should this permission system be enabled by the config ?
It is not in damas-core default behavior to prevent users from reading nodes they don't own.

**Comment by remyla** [comment]
absolutely: this system should be activated/de-activated from conf.json. I modify the issue description to add a note about it

**Comment by juliearesu** [comment]
We have to consider `/api/upsert` as well. I know it wasn't implemented yet but I'm pointing it out just in case.
