### ISSUE TITLE
HTTP PUT DELETE methods

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#20]
Right now the Php web service listens to POST or GET HTTP methods only - make it listen to PUT and DELETE methods according to strict CRUD specifications (please see http://en.wikipedia.org/wiki/Create,_read,_update_and_delete)

Operation |SQL | HTTP
--- | --- | ---
Create | INSERT | PUT / POST
Read (Retrieve) | SELECT | GET
Update (Modify) | UPDATE | PUT / PATCH
Delete (Destroy) | DELETE | DELETE

**Comment by remyla** [comment]
@Baenshee

**Comment by Baenshee** [comment]
Working on it
