### ISSUE TITLE
server-nodejs: key-based permissions in /api/update

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#212]
in conjunction with userclass-based permissions (operation wise), author-based permissions (node wise),

we would like to prevent some keys to be modified with /api/update, unless the user is admin.

* class
* active
* author
* time
* username

this list would be available in conf.json

**Comment by zankia** [comment]
Why does it have to be only for `/api/update` ? (A user can use delete then create to bypass this permission)

Is it wise to replace some key's values by a default one ?
This would allow the user to set a specific key, with a server verification on the validity of this key.
Examples:
* class -> 'guest'
* active -> false

Other keys would be totally erased like so:
* key -> null
