### ISSUE TITLE
server-nodejs: store user last activity time

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#218]
We would like to store the time for each operation the user calls. We could store it under the user's node, in the `lastActivity` key.
```json
{
    "lastlogin":1552872914000,
    "lastActivity":1555665746000,
    "username":"demo",
    "password":""
}
```

This could be implemented as a new extension available in server-nodejs/extensions/.

This feature was requested by @GameFusion

**Comment by GameFusion** [comment]
I think this is an excellent idea! Very usefull for production.
