### ISSUE TITLE
RESTful servers testing

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#29]
In server-tests/, write the procedures to test the HTTP servers (Php and NodeJS)

        `-- damas-core/
            |-- server-tests/

We are going to use an existing framework as http://frisbyjs.com/ in order to send HTTP queries and test the HTTP answers
* evaluate frisbyjs
* write the more tests possible for the CRUD operations
* test both Php and NodeJS servers - raise errors as issues on GitHub https://github.com/remyla/damas-core/issues

**Comment by jogal360** [comment]
Working on it
