### ISSUE TITLE
static route to serve the client interface

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#42]
We now need to run web interfaces to connect to the server, using damas.js

The client interfaces need to be served by the same server (same IP or domain and same port) in order no to be considered as XSS by the web browsers.

For this, we will create a static route that will serve any content from a directory, and thus that will allow us to install our clients in it

Please see http://expressjs.com/starter/static-files.html

The static path to be served can be configured in the conf.json configuration file. The default value will be a 'static' folder as this:

    `-- damas-core/
        |-- server-nodejs/
        |   `-- static/               -- served files here

The static path could be either written in conf.json as an absolute or a relative path.
It could be useful to be able to configure multiple static folders, specifying the mount path for each directory

@jogal360

**Comment by jogal360** [comment]
Working on it.
