### ISSUE TITLE
certificate existence test for HTTPS server

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#53]
before trying to start the https server we should test if the cerFile and keyFile options exist in conf.

these options might be commented by default, so that the http server can start

**Comment by jogal360** [comment]
Working on it.

If it is not defined cerFile and keyFile in conf, if they are not readable or they are not found. Might we launch for default a http connexión?

**Comment by remyla** [comment]
yes, exactly.

by default:

* these options are commented out
* so the the creation of the https server is skipped
* the http server is launched

**Comment by remyla** [comment]
the submitted code will not work, sorry.

1. you try to start the http server only if you have certificate for the https
2. you use fs.access as asynchronous but you process the error as a returned value (synchronous)

what you can do:
* focus on the existence of options in conf (by the way, no need for pathKey - cerFile and KeyFile are sufficient, describing the path to the files to use) - provide a working code without fs tests.
* if the conf for a key and a certificate is available, try to start the https. start the http server anyway.

**Comment by remyla** [comment]
please carefully read the description of this issue:

"before trying to start the https server we should test if the cerFile and keyFile options exist in conf.
these options might be commented by default, so that the http server can start"

we only need this working as described in order to close this issue

**Comment by jogal360** [comment]
@remyla - New version - pull request
