### ISSUE TITLE
Apache URL rewrite for Php

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#55]
Write the Apache url rewrite directives for server-php in order to listen to the same routes as the NodeJS server.

        //
        // CRUDS operations
        //
        app.post('/', create);
        app.get('/:id', read);
        app.put('/:id', update);
        app.delete('/:id', deleteNode);
        app.get('/search/:query',search);
Write the documentation for this, and the directives in the README.md under the server-php/ directory

@jogal360

**Comment by remyla** [comment]
@jogal360 is this possible to integrate your work in order to close this issue?
thanks in advance

**Comment by jogal360** [comment]
Here the code for .htaccess:

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    Rewriterule ^([0-9]+)$ model.crud.php?id=$1 [QSA,L]
    Rewriterule ^(.*)$ model.crud.php [QSA,L]
</IfModule>

**Comment by remyla** [comment]
thanks
