### ISSUE TITLE
/api/search_mongo : regexp options

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#96]
Modify our regexp string encapsulation for json, in order to allow to specify options in it:

for now

```
"REGEXP_<exp>" gives /<exp>/
```

we would want

```
"REGEXP_/<exp>/<options>" to give /<exp>/<options>
```

issue by @sebcourtois, zombillenium

**Comment by MatLala** [comment]
Proposal to send in the query search_mongo a string in this format :
 REGEX_[option]_valuesearch
'option' between brackets can be : i, m, x, s

The new RegExp object will use a generic replace method to be well prepared.

**Comment by MatLala** [comment]
Commit with a new RegExp object prepared with options processed if necessary.

Regexp string encapsulation with : 
"REGEX_/<exp>/<options>"

**Comment by remyla** [comment]
how can I fetch this commit?

**Comment by remyla** [comment]
The code from @MatLala pull request #167 

```js
-                    if (0 === obj[key].indexOf('REGEX_')) {
-                        obj[key] = new RegExp(obj[key].replace('REGEX_', ''));
-                    }
+                    if (0 === obj[key].indexOf('REGEX_/')) {
+						var exp = obj[key].substring(7, obj[key].lastIndexOf('/'));
+						var opt = obj[key].substr(obj[key].lastIndexOf('/')+1);
+						obj[key] = new RegExp(exp, opt);
+					}
```

is good but needs some adjustments:
* we would like to be backward compatible (keep REGEX_ older behavior, else the external code will need to be updated)
* a test about the existence of the second / is needed, else substr will not return what we expect

**Comment by juliearesu** [comment]
Some issues might occur with specific cases such as expressions containing slashes. 
We have to make sure we can differentiate delimiters for the expression and options from any character in the string. 
For example, REGEX_/ could very well be applied for files with a slash in it, but it is also an indicator for regex expressions with options. So tests applied in the code could be incorrect if we don't take these special cases into account.

We might want to change the delimiter character or/and have the client escape characters in the string.
