### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by gnoxr** [remyla/damas-core#99]
We should follow defined coding practices, and therefore choose guidelines among these :
- [Google guidelines](https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting)
- [Crockford's conventions](http://javascript.crockford.com/code.html)
- [Node.js Style Guide](https://github.com/felixge/node-style-guide)
- [Idiomatic.js Principles](https://github.com/rwaldron/idiomatic.js)

I will work on a comparison of these conventions.

**Comment by gnoxr** [comment]
All the guides agree on the importance of keeping semicolons.
Opening brackets should be on the same line in order to avoid implicit statements end, eg :
```js
while (condition)
{
    instruction;
}
```
Can be interpreted by JavaScript as :
```js
while (condition); // infinite loooop
{ instruction; }
```

Both Google and Crockford prefer four spaces over tabs, Node.js and Idiomatic.js use two spaces. Idiomatic.js is the only one accepting tabs.

Crockford made a JS quality tool, [JSLint](http://jslint.com/), that we can use to validate the consistency of our code regarding the Crockford's conventions.
There is also a more laxist tool (which does not exactly follow Crockford's conventions) called [JSHint](http://jshint.com/).

**Comment by zankia** [comment]
As [this page](https://github.com/remyla/damas-core/wiki/Contributing) exists and has not been updated since a while, can we consider this issue closed ?
